
name: Build a tool image container containing a single tool or toolchain.

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      llvm_ref:
        description: 'LLVM reference to check out'
        required: false
        default: 'main'
      tool_id:
        description: 'The tool string used to identify the tool by compiler explorer infra. For example "tools/ninja 1.11.1" or "compilers/c++/clang 13.0.0"'
        required: true
        type: string
      enable_nightly:
        description: 'Enable nightly builds'
        required: false
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'
      dry_run:
        description: 'Dry run'
        required: false
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout llvm-project
      uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        ref: ${{ github.event.inputs.llvm_ref }}
        path: llvm-project
        sparse-checkout: |
          libcxx/utils/ci/
    - name: Checkout builder source
      uses: actions/checkout@v4
      with:
        path: builders/
    # Create a "date" stamp for the output file
    - name: Create output file
      run: |
        echo "image_tag=" > "$GITHUB_OUTPUT"
        echo "image_id=" >> "$GITHUB_OUTPUT"
    - name: Extract image tag
      id: extract_image_tag
      env:
        TOOL_ID: ${{ github.event.inputs.tool_id }}
        TAG_SUFFIX: ${{ github.event.inputs.tag_suffix }}
      run: |
        name=$(echo $TOOL_ID | cut -d' ' -f1 | rev | cut -d'/' -f1 | rev)
        version=$(echo $TOOL_ID | cut -d' ' -f2)
        random_id=$(head -c 10 /dev/random | shasum | head -c 6)
        echo "Using final tag $name-$version-$(date -I)"
        echo "image_tag=$name-$version-$(date -I)" >> "$GITHUB_OUTPUT"
    - name: Build Docker image
      working-directory: builders/
      run: |
        docker build \
          --build-arg "TOOL_ID=${{ github.event.inputs.tool_id }}" \
          --build-arg "NIGHTLY=${{ github.event.inputs.enable_nightly }}" \
          -t ghcr.io/libcxx/tools:${{ steps.extract_image_tag.outputs.image_tag }} \
          -f Dockerfile.compilers  .
    - name: Log in to GitHub Container Registry
      if: ${{ github.event.inputs.dry_run }} == 'false'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image
      if: ${{ github.event.inputs.dry_run == 'false' }}
      run: |
        docker push ghcr.io/libcxx/tools:${{ steps.extract_image_tag.outputs.image_tag }}
      env:
        TAG: ${{ github.event.inputs.tag }}
      working-directory: builders/


