
name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      llvm_ref:
        description: 'LLVM reference to check out'
        required: false
        default: 'main'
      target:
        description: 'Target for Docker build'
        type: choice
        options:
          - 'actions-builder'
          - 'buildkite-builder'
          - 'android-buildkite-builder'
      tag:
        description: 'Tag for Docker image'
        required: false
        default: 'testing'
      dry_run:
        description: 'Dry run'
        required: false
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout llvm-project
      uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        ref: ${{ github.event.inputs.llvm_ref }}

    - name: Build Docker image
      working-directory: libcxx/utils/ci
      run: docker compose build --pull ${{ github.event.inputs.target }}
      env:
        TAG: ${{ github.event.inputs.image }}

    - name: Log in to GitHub Container Registry
      if: ${{ github.event.inputs.dry_run }} == 'false'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      if: ${{ github.event.inputs.dry_run }} == 'false'
      run: |
        docker compose push ${{ github.event.inputs.target }}
      env:
        TAG: ${{ github.event.inputs.tag }}


