
name: Tag a docker image

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'The image to retag'
        type: choice
        options:
          - 'actions-builder'
        default: 'actions-builder'
      source_tag:
        description: 'The source tag to retag'
        required: true
      new_tag:
        description: 'The new tag. Use "live" to deploy to production.'
        required: true

jobs:
  tag-container:
    runs-on: ubuntu-latest

    steps:
    - name: Pull image
      run: docker pull ghcr.io/libcxx/${{ github.event.inputs.image }}:${{ github.event.inputs.source_tag }}

    - name: Retag image
      run: |-
        docker tag ghcr.io/libcxx/${{ github.event.inputs.image }}:${{ github.event.inputs.source_tag }} \
                   ghcr.io/libcxx/${{ github.event.inputs.image }}:${{ github.event.inputs.new_tag }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push ghcr.io/libcxx/${{ github.event.inputs.image }}:${{ github.event.inputs.new_tag }}


